coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 10%
    patch:
      default:
        target: 30%
ignore:
  - "src/main/java/com/karankumar/bookproject/BookProjectApplication.java"
